import React from "react";
import Document, {Html, Head, Main, NextScript} from 'next/document'
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";


class MyDocument extends Document {
    render() {
        return (
            <Html lang="ja">
                <Head>
                    <title>Rabbit Hana</title>
                    <meta name="description" content="Generated by create next app"/>
                </Head>
                <body className={'max-w-screen-[lg] items-center'}>
                <Navigation/>
                <Main/>
                <Footer/>
                <NextScript/>
                </body>
            </Html>
        )
    }
}

export default MyDocument
