import Head from 'next/head'
import HeroSection from "../components/HeroSection";
import PricingSection from "../components/PricingSection";
import ServicesSection from "../components/ServicesSection";
import FAQSection from "../components/FAQSection";
import React from "react";
import publicApi from './api/publicApi';
import {GetStaticPropsContext} from "next";
import ContactSection from "../components/ContactSection";

export default function Home({mainMessage, services, plans, faqs}: any) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <HeroSection mainMessage={mainMessage}/>
            <ServicesSection services={services}/>
            <PricingSection plans={plans}/>
            <FAQSection faqs={faqs}/>
            <ContactSection/>
        </div>
    )
}


export async function getStaticProps(context: GetStaticPropsContext) {
    const [mainMessageData, serviceData, planData, faqData] = await Promise.all(
        [
            publicApi('/message'), publicApi('/services'), publicApi('/plans'),
            publicApi('/faqs')
        ]);
    return {
        props: {
            mainMessage: mainMessageData,
            services: serviceData,
            plans: planData,
            faqs:faqData
        },
        revalidate: 60
    }
}